ADD_START, \
ADD_QUESTION, \
GET_API_KEY, \
END, \
EDIT_BOT , \
GET_BOT , \
CREATE_BOT , \
CHOOSE_BOT , \
CHOOSE_BOT_CHATS , \
VIEW_CHATS , \
START_AGAIN , \
ADD_EDGE , \
ADD_EDGE2 , \
ADD_TEXT_BOX , \
ADD_TEXT_BOX2 , \
ADD_BOX_BUTTON , \
PRINT_BOT , \
HELP , \
MAIN_MENU , \
ADD_BOX_BUTTON2 , \
ADD_BOX_BUTTON3 , \
GET_KEY_FROM_RESPONSE , \
GET_MESSAGE_TO_USER , \
GET_QUERY_PARAMS , \
GET_AUTHORIZATION , \
GET_ENDPOINT , \
GET_BASE_API , \
START_API_FLOW , \
CHOOSE_BOX , \
BOX_DECISION , \
ADD_API_BOX , \
TIMER_ACTION2 , \
TIMER_ACTION3 , \
TIMER_ACTION , \
USER_VARIABLE , \
USER_VARIABLE2 , \
USER_VARIABLE3 , \
ADD_USER_VARIABLE , \
INIT_BOT , \
GET_INTERNAL_VARIABLE , \
INTERNAL_VARIABLE_SOURCE , \
INTERNAL_VARIABLE_INSTANT_VALUE , \
INTERNAL_VARIABLE_API_VALUE , \
INTERNAL_VARIABLE_API_HEADERS , \
INTERNAL_VARIABLE_API_MAPPING , \
INTERNAL_VARIABLE_ASSIGNMENT_START_FLOW , \
CHOOSE_NODE_TO_DELETE , \
DELETE_NODE = range(48)